apiVersion: v1
kind: Pod
metadata:
  name: vault-test-app
  namespace: vault-book
  annotations:
    # InjectorによるVault Agentの挿入を有効化
    vault.hashicorp.com/agent-inject: "true"

    # 明示的にjwtを指定する。
    vault.hashicorp.com/auth-type: "jwt"

    # jwtでの認証において必要なService Accountのトークンの絶対パスを指定する。
    vault.hashicorp.com/auth-config-path: "/var/run/secrets/kubernetes.io/serviceaccount/token"

    # 使用するVault上のRoleを指定
    vault.hashicorp.com/role: "vault-jwt-app"

    # Pod内に/vault/secrets/app-config.txtというファイルが作成され秘密情報が記載される
    vault.hashicorp.com/agent-inject-secret-app-config.txt: "secret/data/app/config"
  labels:
    app: nginx
spec:
  serviceAccountName: app
  containers:
  - name: nginx
    image: nginx:alpine