apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jwt-vault-secret-1
  namespace: vault-book
spec:
  vaultAuthRef: jwt-vault-auth
  type: kv-v2
  mount: secret
  path: app/config
  refreshAfter: 60s
  destination:
    create: true
    name: app-secret-from-vso-jwt