---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  name: app-vault-static-secret
  namespace: default
spec:
  vaultAuthRef: app-vault-auth  # VaultAuthを指定
  type: kv-v2
  mount: secret
  name: app/config
  refreshAfter: 60s
  destination:
    create: true
    name: app-secret-from-vso  # Kubernetes上に作成されるSecretリソース名