apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: app-vault-auth
  namespace: default
spec:
  vaultConnectionRef: app-vault-connection # VaultConnectionを指定
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: app  # Vault上のRoleを指定
    serviceAccount: app  # Vault上の秘密情報を取得するためのService Accountを指定