apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: pki-vault-secret
  namespace: default
spec:
  vaultAuthRef: pki-vault-auth
  mount: pki_k8s                             # PKI Secret Engineを有効化したパス
  role: vault-book-com-vso                   # 証明書の発行に対するロール
  commonName: example-vso.vault-book.com     # Subject common Name
  format: pem                                # 証明書のフォーマット
  expiryOffset: 30s                          # 失効する日時に対するオフセット
  ttl: 720h                                  # 証明書のTTL
  revoke: true                               # VaultPKISecretリソース削除時に証明書を無効化するかどうか
  clear: true                                # VaultPKISecretリソース削除時にSecretリソースを削除するかどうか
  destination:
    create: true
    name: vso-vault-book-com-tls