apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: pki-vault-secret
  namespace: default
spec:
  vaultAuthRef: pki-vault-auth
  mount: pki_k8s
  role: vault-book-com-vso
  commonName: example-vso.vault-book.com
  format: pem
  expiryOffset: 30s
  ttl: 720h
  revoke: true
  clear: true
  destination:
    create: true
    name: vso-vault-book-com-tls
    type: kubernetes.io/tls