apiVersion: v1
kind: Pod
metadata:
  name: app-vault-agent-dynamic
  labels:
    app: app-vault-agent-dynamic
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'app'
    vault.hashicorp.com/agent-inject-secret-app-config.txt: 'database/creds/workshop-role'
    vault.hashicorp.com/agent-inject-template-app-config.txt: |
      {{- with secret "database/creds/workshop-role" -}}
      export username="{{ .Data.username }}"
      export password="{{ .Data.password }}"
      {{- end -}}
spec:
  containers:
  - name: app
    image: ubuntu:22.04
    command: ["/bin/bash", "-c", "source /vault/secrets/app-config.txt && echo $username && echo $password && /bin/sh -c 'while :; do sleep 10; done'"]
  serviceAccountName: app