apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: mysql-dynamic-secret
  namespace: default
spec:
  vaultAuthRef: app-vault-auth
  mount: database
  path: creds/workshop-role
  destination:
    create: true
    name: mysql-secret-from-vso